
export const routes = [
  {
    path:"/membre",
    name:"Membres",
    single:"Membre"
   },
   {
    path:"/entreprise",
    name:"Entreprises"
    ,
    single:"Entreprise"
   },
   {
    path:"/pays",
    name:"pays",
    single:"pays"
   },
   {
    path:"/ville",
    name:"Villes",
    single:"Ville"
   },
   {
    path:"/quartier",
    name:"Quartiers",
    single:"Quartier"
   },
   {
    path:"/caisse",
    name:"Caisses",
    single:"Caisse"
   },
]